### ISSUE TITLE
Bluenet sometimes crashes with an exception

### ISSUE THREAD

**Issue by grunskis** [getsenic/senic-hub#164] opened 2017-06-09 10:10 UTC
```
[75715.517248] Unable to handle kernel NULL pointer dereference at virtual address 00000040
[75715.525384] pgd = deeb8000
[75715.528096] [00000040] *pgd=5efd5835, *pte=00000000, *ppte=00000000
[75715.534402] Internal error: Oops: 17 [#21] SMP ARM
[75715.539205] Modules linked in: mt7601u senic_button(O) mac80211 cfg80211
[75715.545927] CPU: 2 PID: 278 Comm: dbus-daemon Tainted: G      D W  O    4.10.0 #1
[75715.553398] Hardware name: Allwinner sun8i Family
[75715.558100] task: deead940 task.stack: de82e000
[75715.562637] PC is at unix_detach_fds+0x18/0x4c
[75715.567079] LR is at unix_stream_read_generic+0x788/0x82c
[75715.572473] pc : [<c05bc444>]    lr : [<c05bdd9c>]    psr: 200e0013
[75715.572473] sp : de82fda8  ip : 0000001c  fp : de82fe4c
[75715.583935] r10: deebc77c  r9 : deebc5fc  r8 : 00000124
[75715.589154] r7 : 000006dc  r6 : deebc580  r5 : 00000000  r4 : da978780
[75715.595672] r3 : 00000040  r2 : 00000040  r1 : da978780  r0 : de82fdf8
[75715.602191] Flags: nzCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
[75715.609315] Control: 10c5387d  Table: 5eeb806a  DAC: 00000051
[75715.615052] Process dbus-daemon (pid: 278, stack limit = 0xde82e210)
[75715.621397] Stack: (0xde82fda8 to 0xde830000)
[75715.625751] fda0:                   da978780 00000000 deebc580 c05bdd9c 00000010 00000050
[75715.633919] fdc0: 00000000 00000124 00000000 00000124 00000000 00000000 00000000 00000001
[75715.642087] fde0: df02d800 deebc744 00000001 00000000 de82e000 00000001 00000000 00000040
[75715.650256] fe00: 00000000 00000000 00000000 0000004c df02d800 c0341efc de82fe78 de82fe24
[75715.658426] fe20: 00000000 de82ff6c 00000000 40000040 be8ce8bc be8ce848 de82feb8 df02d800
[75715.666595] fe40: be8ce8fc c05bdf00 dffd6640 c05bc400 df02d800 de82ff6c 00000000 00000800
[75715.674763] fe60: 40000040 00000000 de82feb8 c052dd78 00000000 00000000 03e6c410 00000800
[75715.682931] fe80: de97b300 de97b330 00000000 c052c82c da854f0c de82fed8 00000000 de82ff58
[75715.691098] fea0: de97b300 c022c77c 00000000 00000019 dee1dab8 c022c704 de97b300 de97b330
[75715.699267] fec0: de82fed8 de82ff58 00000000 00000000 de97b300 c022d2b8 de82fed8 de82fed8
[75715.707435] fee0: dffd9800 00000040 be8ce570 00000000 df5e7600 df5e7600 de97b300 00000000
[75715.715604] ff00: 00033d80 c022e164 00000000 dee1c000 00000001 dea5a4c0 dee1c018 dffd6640
[75715.723772] ff20: de97b330 dea5a4c0 00000000 00000000 00000000 be8ce764 be8ce8bc 40000000
[75715.731939] ff40: df02d800 00000129 c0107644 de82e000 00000000 c052ebc8 00000000 be8ce570
[75715.740108] ff60: 00000000 00000000 fffffff7 00000000 00000000 00000000 00000124 000006dc
[75715.748276] ff80: de82fe78 00000001 be8ce848 0000004c 40000000 00000000 be8ce914 02c3802c
[75715.756445] ffa0: 033f36c0 c0107480 be8ce914 02c3802c 0000000f be8ce8bc 40000000 00000000
[75715.764614] ffc0: be8ce914 02c3802c 033f36c0 00000129 0000004c be8ce8bc 0000000f be8ce8fc
[75715.772783] ffe0: b6fa8c18 be8ce830 b6f8e158 b6f13318 600e0010 0000000f 00000000 00000000
[75715.780967] [<c05bc444>] (unix_detach_fds) from [<c05bdd9c>] (unix_stream_read_generic+0x788/0x82c)
[75715.790004] [<c05bdd9c>] (unix_stream_read_generic) from [<c05bdf00>] (unix_stream_recvmsg+0x3c/0x44)
[75715.799217] [<c05bdf00>] (unix_stream_recvmsg) from [<c052dd78>] (___sys_recvmsg+0x90/0x164)
[75715.807648] [<c052dd78>] (___sys_recvmsg) from [<c052ebc8>] (__sys_recvmsg+0x3c/0x68)
[75715.815476] [<c052ebc8>] (__sys_recvmsg) from [<c0107480>] (ret_fast_syscall+0x0/0x3c)
[75715.823389] Code: e5912024 e5802004 e5813024 e5903004 (e1d340f0)
[75715.829583] ---[ end trace 0ffe9ca22196e0bb ]---
[75715.856857] wlan0: deauthenticating from 06:8d:db:18:26:0b by local choice (Reason: 3=DEAUTH_LEAVING)
```

Command I used to run bluetnet:

```
/srv/senic_hub/venv/bin/bluenetd -b hci0 -w wlan0 start -v -d http://192.168.1.19:6543/-/ -a 'Senic Hub'
```

**Comment by larsblumberg** [comment] 2017-07-24 09:40
This exception could be the same as described here: https://github.com/getsenic/senic-os/issues/9#issuecomment-316931012

**Comment by rudolfs** [comment] 2017-07-24 12:13
Duplicate of https://github.com/getsenic/senic-os/issues/9#issuecomment-316931012

**Closed by rudolfs** 2017-07-24 12:13 UTC
